# Список серверов-лобби (имена, как указано в BungeeCord)
lobby_servers:
  - "lobby"

# Список серверов, на которых команды /lobby и /hub заблокированы
disabled_servers:
  - "auth"

# Сообщения
messages:
  no_permission: "&cУ вас нет прав на выполнение этой команды."
  only_players: "&cЭта команда может быть выполнена только игроком."
  player_not_found: "&cИгрок не найден."
  reload_success: "&aКонфигурация успешно перезагружена."
  successfully_sent: "&aВы были перемещены в лобби."
  no_lobby_server: "&cНет доступных лобби серверов."
  already_on_lobby: "&cВы уже находитесь на лобби-сервере!"
  disabled_server: "&cНа этом сервере использование данной команды запрещено."